language: go

go:
  - "1.11.x"

git:
  depth: 1

notifications:
  email: false


install: go get

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $HOME/bin v1.12.5

script:
  - golangci-lint run
  - go test
