apiVersion: v1
kind: Service
metadata:
  name: validating-admission-webhook
  namespace: validating-admission-webhook
  labels:
    app: validating-admission-webhook
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: validating-admission-webhook
