apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: good-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
spec:
  # The rest fills in some required fields.
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
